OUT				= test.out

PROJECT			= ft_atoi

MAIN			= main.c

COMPILE			= ft_atoi.c

WWW				= -Wall -Wextra -Werror

all:
	gcc ${WWW} ${PATH_PROJECT}/${COMPILE} ${MAIN} -o ${OUT}

clean:
	rm -rf *.o

fclean:			clean
	rm -rf ${OUT}
