int		test_ft_strlen(char *str);
int		test_ft_atoi(char *str);
int		test_ft_strjoin(char *correct, char *str_1, char *str_2);
int		test_ft_strcmp(char *str_1, char *str_2);
int		test_ft_strncmp(char *str_1, char *str_2, char *n);
int		test_ft_itoa(char *str);
int		test_ft_isascii(char *str);
int		test_ft_isprint(char *str);
int		test_ft_isdigit(char *str);
int		test_ft_isalpha(char *str);
int		test_ft_isalnum(char *str);
int		test_ft_toupper(char *str);
