OUT				= test.out

PROJECT			= ft_strlen

PATH_PROJECT	= /Users/e.balabanov/Desktop/Projects/21_school

MAIN			= main.c

COMPILE			= ft_strlen.c

WWW				= -Wall -Wextra -Werror

all:
	gcc ${WWW} ${PATH_PROJECT}/${COMPILE} ${MAIN} -o ${OUT}

clean:
	rm -rf *.o

fclean:			clean
	rm -rf ${OUT}
