OUT			= test.out

PATH_PROJECT	= /Users/e.balabanov/Desktop/Projects/moulinet/projects/ft_strlen/

MAIN		= main.c

SRC 		= /Users/e.balabanov/Desktop/Projects/21_school/

COMPILE		= ft_strlen.c

WWW			= -Wall -Wextra -Werror

all:
	gcc ${WWW} ${SRC}${COMPILE} ${PATH_PROJECT}${MAIN} -o ${PATH_PROJECT}${OUT}

clean:
	rm -rf ${PATH_PROJECT}*.o

fclean:
	rm -rf ${PATH_PROJECT}${OUT}
