OUT				= test.out

PROJECT			= `s

MAIN			= main.c

COMPILE			= ${PROJECT}.c

WWW				= -Wall -Wextra -Werror

all:
	gcc ${WWW} ${PATH_PROJECT}/${COMPILE} ${MAIN} test.c -o ${OUT} -I ./include/

clean:
	rm -rf *.o

fclean:			clean
	rm -rf ${OUT}
